### ISSUE TITLE
ET Node Version erroring

### ISSUE THREAD

**Issue by AL6981** [LaunchAcademy/extraterrestrial#33]
**Describe the bug**
When I REMOVE the Ruby `et` gem and install the node version, I try to `get` something:
```
(node:57695) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected number in JSON at position 1
    at JSON.parse (<anonymous>)
    at Function.loadFromFile (/Users/amylynn/.nvm/versions/node/v11.0.0/lib/node_modules/extraterrestrial/src/Configuration.js:29:35)
    at Function.loadFromDirectory (/Users/amylynn/.nvm/versions/node/v11.0.0/lib/node_modules/extraterrestrial/src/Configuration.js:43:26)
    at /Users/amylynn/.nvm/versions/node/v11.0.0/lib/node_modules/extraterrestrial/bin/et-get:13:32
    at Object.<anonymous> (/Users/amylynn/.nvm/versions/node/v11.0.0/lib/node_modules/extraterrestrial/bin/et-get:22:3)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
(node:57695) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:57695) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Using **Node 14.4.0 I cannot submit, I see this error message:**
`Lesson directory not found.`

```
➜  challenges nvm ls
         v8.9.0
       v10.15.3
        v11.0.0
       v12.16.3
        v14.4.0
->       system
default -> 11.0 (-> v11.0.0)
node -> stable (-> v14.4.0) (default)
stable -> 14.4 (-> v14.4.0) (default)
iojs -> N/A (default)
lts/* -> lts/erbium (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.17.0 (-> N/A)
lts/dubnium -> v10.21.0 (-> N/A)
lts/erbium -> v12.18.1 (-> N/A)
➜  challenges nvm use 14.4.0
Now using node v14.4.0 (npm v6.14.5)
➜  challenges yarn global add extraterrestrial
yarn global v1.12.3
[1/4] 🔍  Resolving packages...
warning extraterrestrial > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
[2/4] 🚚  Fetching packages...
error https://registry.yarnpkg.com/event-stream/-/event-stream-3.3.6.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "Unexpected end of data"
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
➜  challenges et submit bank-account-js
Lesson directory not found.
```

**Comment by dpickett** [comment]
are you running `et submit` from within the lesson directory?

**Comment by CassandraNewell** [comment]
note that this issue actually pertains to this app: https://github.com/LaunchAcademy/extraterrestrial-node

@AL6981 , based on the first error, I believe the issue is that you need to `et init` again (the Ruby .et file is... yml?... and the Node .et file is json, so you'll get a parsing error otherwise

**Comment by dpickett** [comment]
you had it right @CassandraNewell - we were in a ruby world trying to play a JSON game.
